### ISSUE TITLE
UsageError: Line magic function `%sql` not found.

### ISSUE THREAD

**Issue by dsm-72** [ploomber/jupysql#904]
### What happens?

So it seems that even if using jupysql you still need ipython-sql
[SO question](https://stackoverflow.com/questions/63882681/usageerror-line-magic-function-sql-not-found)

### To Reproduce

```yml
name: bug

channels:
- conda-forge


dependencies:
- python>=3.10

# Jupyter Notebooks
# --------------------------------------------------------------------------------
- conda-forge::notebook
- conda-forge::ipykernel
- conda-forge::ipywidgets
- conda-forge::jupysql


# Data Science
# --------------------------------------------------------------------------------
- pandas
- pyarrow

```
Then
```shell
%load_sql
%sql ...
```

### OS:

macOS

### JupySQL Version:

latest 0.10.1

### Full Name:

dsm72

### Affiliation:

school
